language: generic
sudo: required
services:
  - docker
  

before_install:
  - docker build -t onlyjoshn/docker-react -f Dockerfile.dev .

script:
  - docker run onlyjoshn/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-us-west-1-695432948440
  bucket_path: docker
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: $AWS_SECRET_KEY